name: outline
image:
  repository: outlinewiki/outline
  tag: 0.69.1
  pullPolicy: IfNotPresent
replicas: 1
resources: {}

redis:
  enabled: true
  architecture: "standalone"
  persistence:
    size: 2Gi
    storageClass: ""
  auth:
    enabled: false
